#!/usr/bin/env python3


"""
Visualize matches between query and reference images.
"""


import os
import argparse
from typing import Any, Literal, overload

import numpy as np
import cv2
import h5py
from tqdm import tqdm
import matplotlib.pyplot as plt


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--match_file",
        type=str,
        help="HDF5 file generated by Hloc containing local feature matches",
    )
    parser.add_argument(
        "--feat_file_query",
        type=str,
        help="HDF5 file generated by Hloc containing local features of query images",
    )
    parser.add_argument(
        "--feat_file_ref",
        type=str,
        help="HDF5 file generated by Hloc containing local features of reference images",
    )
    parser.add_argument(
        "--image_dir_query",
        type=str,
        help="Paths to the directory with query images corresponding to the input files, "
        "used to get camera resolution for USD files",
    )
    parser.add_argument(
        "--image_dir_ref",
        type=str,
        help="Paths to the directory with reference images corresponding to the input files, "
        "used to get camera resolution for USD files",
    )
    parser.add_argument(
        "--pairs_dir",
        type=str,
        help="Path to the output directory where the figures of image pairs with matches will be generated",
    )
    parser.add_argument(
        "--limit_to_queries",
        type=str,
        nargs="+",
        help="List of query image names for which the figures will be generated",
    )
    parser.add_argument(
        "--limit_to_refs",
        type=str,
        nargs="+",
        help="List of reference image names for which the figures will be generated",
    )
    parser.add_argument(
        "--subset_n",
        type=int,
        default=40,
        help="Show only a subset of all the matches. Random subset if > 0, subset with the best scores if < 0, all if = 0.",
    )
    parser.add_argument(
        "--ref_info",
        type=str,
        help="Path to the reference camera information (intrinsics and extrinsics) - used only for computation of Samspon error",
    )
    parser.add_argument(
        "--color_mode",
        type=str,
        default="score",
        choices=["random", "score"],
        help="How to color the match lines",
    )
    parser.add_argument(
        "--color_val_min",
        type=float,
        help="Minimal value of score for coloring the match lines - default 0.0",
        default=0.0,
    )
    parser.add_argument(
        "--color_val_max",
        type=float,
        help="Maximal value of score for coloring the match lines - default 1.0",
        default=1.0,
    )
    args = parser.parse_args()

    np.random.seed(seed=42)

    mf = h5py.File(args.match_file, "r", libver="latest")
    query_name_list = list(mf.keys())

    pbar = tqdm(total=count_match_pairs(mf))
    for query_name in query_name_list:
        if (args.limit_to_queries is not None and 
            len(args.limit_to_queries) > 0 and 
            query_name not in args.limit_to_queries):
            continue

        query_keypoints = np.array(
            get_keypoints(args.feat_file_query, query_name)
        ).astype(float)
        query_path = os.path.join(args.image_dir_query, query_name)
        assert os.path.isfile(query_path)
        query_image = cv2.imread(query_path)
        assert query_image is not None
        query_h, query_w, _ = query_image.shape

        ref_name_list = list(mf[query_name].keys())

        for ref_name in ref_name_list:
            if (args.limit_to_refs is not None and 
                len(args.limit_to_refs) > 0 and 
                ref_name not in args.limit_to_refs):
                continue

            ref_keypoints = np.array(
                get_keypoints(args.feat_file_ref, ref_name)
            ).astype(float)
            ref_path = os.path.join(args.image_dir_ref, ref_name)
            assert os.path.isfile(ref_path)
            ref_image = cv2.imread(ref_path)
            assert ref_image is not None
            ref_h, ref_w, _ = ref_image.shape

            # - adapted from https://github.com/cvg/Hierarchical-Localization/blob/master/hloc/utils/io.py
            match_idxs = mf[query_name][ref_name]["matches0"].__array__()
            match_scores = mf[query_name][ref_name]["matching_scores0"].__array__()
            idx = np.where(match_idxs != -1)[0]
            match_idxs = np.stack([idx, match_idxs[idx]], -1)
            match_scores = match_scores[idx]

            if args.subset_n > 0 and match_scores.shape[0] > args.subset_n:
                selected_idxs = np.random.choice(
                    match_idxs.shape[0], args.subset_n, replace=False
                )
                match_idxs = match_idxs[selected_idxs, :]
                match_scores = match_scores[selected_idxs]
            elif args.subset_n < 0 and len(match_scores) > -args.subset_n:
                order_idx = np.argsort(match_scores)[args.subset_n :]
                match_idxs = match_idxs[order_idx, :]
                match_scores = match_scores[order_idx]

            query_points2D = query_keypoints[match_idxs[:, 0], :]
            ref_points2D = ref_keypoints[match_idxs[:, 1], :]

            resize_ratio = 1.0 * query_h / ref_h
            ref_image = cv2.resize(ref_image, (0, 0), fx=resize_ratio, fy=resize_ratio)
            ref_h, ref_w, _ = ref_image.shape
            ref_points2D = resize_ratio * ref_points2D

            gap_w = 10
            out_canvas = np.zeros((query_h, query_w + gap_w + ref_w, 3))

            out_canvas[0:, 0:query_w, :] = query_image
            out_canvas[0:, query_w + gap_w :, :] = ref_image

            for line_idx in range(query_points2D.shape[0]):
                query_point = query_points2D[line_idx, :]
                ref_point = ref_points2D[line_idx, :]
                score = match_scores[line_idx]

                if args.color_mode == "random":
                    line_color = [
                        int(val) for val in palette[line_idx % palette.shape[0]]
                    ]
                elif args.color_mode == "score":
                    score_vis = np.clip(
                        score, args.color_val_min, args.color_val_max
                    ) / (args.color_val_max - args.color_val_min)
                    line_color = sample_colorscale(
                        "viridis",
                        [score_vis],
                        low=0.0,
                        high=1.0,
                        colortype="tuple",
                    )[0]
                    line_color = [int(255 * val) for val in line_color]
                    line_color_out = line_color.copy()
                    line_color_out[0] = line_color[2]
                    line_color_out[2] = line_color[0]
                    line_color = line_color_out

                ref_point[0] += query_w + gap_w

                out_canvas = cv2.line(
                    out_canvas,
                    tuple(map(int, query_point)),
                    tuple(map(int, ref_point)),
                    line_color,
                    2,
                )

            if args.color_mode != "random":
                out_canvas = add_colorbar(
                    out_canvas, "viridis", args.color_val_min, args.color_val_max
                )

            out_path = os.path.join(
                args.pairs_dir,
                os.path.splitext(query_name)[0]
                + "_-_"
                + os.path.splitext(ref_name)[0]
                + ".jpg",
            )
            cv2.imwrite(out_path, out_canvas)
            pbar.update(1)

    pbar.close()
    mf.close()


def sample_colorscale(colormap_name, values, low=0.0, high=1.0, colortype="tuple"):
    if colortype != "tuple":
        raise ValueError("Only tuple color output is supported")

    values = np.asarray(values, dtype=float)
    if high == low:
        normalized_values = np.zeros_like(values)
    else:
        normalized_values = np.clip((values - low) / (high - low), 0.0, 1.0)


    colors = plt.get_cmap(colormap_name)(normalized_values)[..., :3]
    return [tuple(color) for color in np.atleast_2d(colors)]


palette = (
    np.array(sample_colorscale("tab20", np.linspace(0.0, 1.0, 20)))[:, ::-1] * 255
).astype(np.uint8)


def add_colorbar(canvas, colormap_name, value_min, value_max):
    font = cv2.FONT_HERSHEY_SIMPLEX
    font_size = 1.2
    font_color = (255, 255, 255)
    font_thickness = 2
    gap_height = 40

    canvas_height = canvas.shape[0]
    canvas_width = canvas.shape[1]
    text_width = 160

    canvas = np.vstack((canvas, np.zeros((gap_height, canvas_width, 3))))

    canvas = cv2.putText(
        canvas,
        "{:.1f}".format(value_min),
        (10, canvas_height + 30),
        font,
        font_size,
        font_color,
        font_thickness,
    )
    canvas = cv2.putText(
        canvas,
        "{:.1f}".format(value_max),
        (canvas_width - text_width + 10, canvas_height + 30),
        font,
        font_size,
        font_color,
        font_thickness,
    )

    vals = np.linspace(0.0, 1.0, canvas_width - 2 * text_width)
    colors = sample_colorscale(colormap_name, vals, low=0.0, high=1.0, colortype="tuple")
    color_bar = np.zeros((gap_height, canvas_width - 2 * text_width, 3))
    for idx, c in enumerate(colors):
        color = np.zeros((1, 1, 3))
        color[0, 0, 2] = int(255 * c[0])
        color[0, 0, 1] = int(255 * c[1])
        color[0, 0, 0] = int(255 * c[2])

        color_bar[:, idx, :] = color
    canvas[canvas_height:, text_width:-text_width, :] = color_bar
    return canvas


def count_match_pairs(f_hdf5):
    total_num = 0
    for refs in f_hdf5.values():
        total_num += len(refs)
    return total_num


@overload
def get_keypoints(path: str, name: str, return_uncertainty: Literal[False] = ...) -> np.ndarray: ...
@overload
def get_keypoints(path: str, name: str, return_uncertainty: Literal[True]) -> tuple[np.ndarray, Any]: ...
def get_keypoints(
    path: str, name: str, return_uncertainty: bool = False
) -> np.ndarray | tuple[np.ndarray, Any]:
    """
    Adapted from Hierarchical-Localization hloc.utils.io.get_keypoints
    """
    with h5py.File(path, "r", libver="latest") as hfile:
        dset = hfile[name]["keypoints"]
        p = dset.__array__()
        uncertainty = dset.attrs.get("uncertainty")
    if return_uncertainty:
        return p, uncertainty
    return p


if __name__ == "__main__":
    main()
